-------------------------------------------------------------------------
-- Copyright (c) 2009 State Street Bank and Trust Corp.
-- 225 Franklin Street, Boston, MA 02110, U.S.A.
-- All rights reserved.
--
-- "GEC_CONSTANTS_PKG.sql is the copyrighted,
-- proprietary property of State Street Bank and Trust Company and its
-- subsidiaries and affiliates which retain all right, title and interest
-- therein."
--
-- Revision History
--
-- Date            Programmer                Notes
-- ------------    --------------------      ----------------------------
-- Apr  4, 2009    Zhao Hong                 initial
--
--
-------------------------------------------------------------------------

create or replace package GEC_CONSTANTS_PKG
as
	--SOURCE_CD
	C_IM_FILE   		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'IM File';
	C_CALL      		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'Call';
	C_SOURCE_X  		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'X';
	C_SYSTEM    		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'System';
	C_IM_UPLOAD 		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'UI - IM File upload';
	C_IM_ENTRY  		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'UI - IM Loc. Entry';
	C_TRADER_ENTRY  	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'UI - Trader Loc. Entry';
	C_IM_CP_PASTE  		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'UI - IM Copy Paste';
	C_IM_AVAIL_ENTRY 	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'UI - IM Avail Enter';
	C_API_LOCATE		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'API';
	C_FA_REQUEST		CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'File-Auto';
	C_FA_SMAC_REQUEST	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'SMAC';
	C_FA_GSMAC_REQUEST	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'GSMAC';
	C_ALL_INLINE_EDIT	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'INLINE-EDIT';
	C_ALL_FUTURE_LOCATE	CONSTANT GEC_SOURCE.SOURCE_CD%TYPE := 'FUTURE-LOCATE';
	
	--ASSET_CODE_TYPE
	C_CSP       CONSTANT GEC_ASSET_IDENTIFIER.ASSET_CODE_TYPE%TYPE := 'CSP';
	C_ISN       CONSTANT GEC_ASSET_IDENTIFIER.ASSET_CODE_TYPE%TYPE := 'ISN';
	C_SED       CONSTANT GEC_ASSET_IDENTIFIER.ASSET_CODE_TYPE%TYPE := 'SED';
	C_QUK       CONSTANT GEC_ASSET_IDENTIFIER.ASSET_CODE_TYPE%TYPE := 'QUK';
	C_TIK       CONSTANT GEC_ASSET_IDENTIFIER.ASSET_CODE_TYPE%TYPE := 'TIK';
	
	--TRANSACTION_CD
	C_LOCATE    CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'LOCATE';
	C_PREBORROW CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'PREBORROW';
	C_SHORT     CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'SHORT';
	C_COVER     CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'COVER';
	C_TRAILER   CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'TRAILER';
	C_SHORT_CANCEL     CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'SHORT CANCEL';
	C_COVER_CANCEL     CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'COVER CANCEL';
	C_SB_SHORT CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE := 'SHORTSB';
	C_FLIP_TRADE CONSTANT GEC_TRANSACTION.TRANSACTION_CD%TYPE :='FT';
	
	--POSITION_FLAG
	C_GC        CONSTANT GEC_IM_AVAILABILITY.POSITION_FLAG%TYPE := 'GC';
	C_SP        CONSTANT GEC_IM_AVAILABILITY.POSITION_FLAG%TYPE := 'SP';
	
	--EXPORT STATUS
	C_INFLIGHT_STATUS	CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE :='I';
	C_INFLIGHT_STATUS_MSG	CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE :='In-Flight';
	C_PENDING_STATUS	CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE :='P';
	C_PENDING_STATUS_MSG	CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE :='Pending';
	
	--EXPORT TRADE BLOTTER TYPE
	C_SB_REQUEST			CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='SB';
	C_SBO_REQUEST			CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='SBO';
	C_NSB_REQUEST			CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='NSB';
	C_EXTERNAL_REQUEST		CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='External';
	C_NC_REQUEST			CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='NC';
	C_FT_REQUEST			CONSTANT GEC_BRW_REQUEST_FILE_TYPE.BORROW_REQUEST_FILE_TYPE%TYPE :='FT';
		
	--GEC_CONFIG ATTR_GROUP
	C_ARCHIVE CONSTANT GEC_CONFIG.ATTR_GROUP%TYPE := 'ARCHIVE';
	C_PURGE CONSTANT GEC_CONFIG.ATTR_GROUP%TYPE := 'PURGE';
	C_DELETE CONSTANT GEC_CONFIG.ATTR_GROUP%TYPE := 'DELETE';
	
	--GEC_CONFIG ATTR_NAME
	C_ACTIVITY_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'ACTIVITY_DAY_WINDOW';
	C_AVAILABILITY_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'AVAILABILITY_DAY_WINDOW';
	C_AVAIL_ERR_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'AVAIL_ERR_DAY_WINDOW';
	C_LOCATE_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'LOCATE_DAY_WINDOW';
	C_MESSAGE_ARCHIVE_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'MESSAGE_ARCHIVE_DAY_WINDOW';
	C_MESSAGE_DELETE_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'MESSAGE_DELETE_DAY_WINDOW';
	C_EXCHAGE_RATE_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'EXCHANGE_RATE_DAY_WINDOW';
	C_ASSET_AUDIT_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'ASSET_AUDIT_DAY_WINDOW';
	C_LENDER_AVAIL_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'LENDER_AVAIL_DAY_WINDOW';
	C_JOB_LOG_DAY_WINDOW CONSTANT GEC_CONFIG.ATTR_NAME%TYPE := 'DB_LOG';
	--ASSET TYPE DESC
	C_CORPBOND 	CONSTANT GEC_ASSET_TYPE.ASSET_TYPE_DESC%TYPE := 'CORP BOND';
	C_EQUITY 	CONSTANT GEC_ASSET_TYPE.ASSET_TYPE_DESC%TYPE := 'EQUITY';
	
	--ASSET LIQUIDITY 
	C_LIQUID CONSTANT VARCHAR2(10)  := 'LIQUID';
	C_ILLIQUID CONSTANT VARCHAR2(10):= 'ILLIQUID';
	C_NALIQUID CONSTANT VARCHAR2(10):= 'N/A';
	C_LIQUID_DB CONSTANT GEC_ASSET.LIQUIDITY_FLAG%TYPE := 'YES';
	C_ILLIQUID_DB CONSTANT GEC_ASSET.LIQUIDITY_FLAG%TYPE := 'NO';
	C_NALIQUID_DB CONSTANT GEC_ASSET.LIQUIDITY_FLAG%TYPE := 'N/A';
	
	--OTHER LITERAL CONSTANTS
	C_SUCCESS CONSTANT VARCHAR2(10) := 'SUCCESS';
	C_FAILURE CONSTANT VARCHAR2(10) := 'FAILURE';
	
	-- -1 is value from java side and it represents the NULL in Oracle.
	C_NULL CONSTANT NUMBER(11)	:= -1;
	
	--****************************************************************
	--Jira-928
	--****************************************************************
	--File with valid and Invalid Strategy (IM and Strategy don't match), default- any of the strategy for that IM 
	C_ERRMSG_INVALID_STRATEGY CONSTANT VARCHAR2(100) := 'FILED FUND INCORRECT:VALID IM and INVALID Strategy.'; 	
	
	--File with valid and Invalid Fund (IM and Fund don't match), default- any of the fund for that IM 
	C_ERRMSG_INVALID_FUND CONSTANT VARCHAR2(100) := 'FILED FUND INCORRECT:VALID IM and INVALID FUND.';
	
	--Import valid file to Active/Inactive IM , who has funds but no Default-Fund, default- any of the fund for that IM 
	C_ERRMSG_NO_DEFAULT_FUND CONSTANT VARCHAR2(100) := 'FILED FUND INCORRECT:VALID IM and NO DEFAULT FUND.';
	
	C_ERRMSG_INVALID_CUSIP CONSTANT VARCHAR2(100) := 'VLD0021: the CUSIP or TICKER field is invalid.'; 
	
	C_ERRMSG_DUPLICATED_TICKER CONSTANT VARCHAR2(100) := 'VLD0038: the locate with a ticker has more than one CUSIP.';
	
	--Invalid Strategy (New API feature) *** check below (required only when Im has multiple strategies) 
	
	--Status of Locate
	C_STATUS_ERROR CONSTANT GEC_LOCATE_PREBORROW.STATUS%type := 'X'; 
	
	--comment length
	C_COMMENT_MAX CONSTANT NUMBER(11)	:= 4000;
	C_LIQUIDITY_COMMENTS CONSTANT VARCHAR2(300) := 'This communication shall be deemed to be a Liquid Shares Notice and shall be governed by the most recent Liquid Shares Notice Terms and Conditions sent to you by ';
	C_ILLIQUIDITY_COMMENTS CONSTANT VARCHAR2(300) := 'This communication shall be deemed to be an Illiquid Shares Notice and shall be governed by the most recent Illiquid Shares Notice Terms and Conditions sent to you by ';
	
	C_GMBH_COMMENTS CONSTANT VARCHAR2(100) := 'State Street Bank GmbH.';
	C_SSBT_COMMENTS CONSTANT VARCHAR2(100) := 'State Street Bank and Trust Company.';

	--legal entity
	C_LEGAL_ENTITY_GMBH CONSTANT VARCHAR2(40) := 'GmbH';
	C_LEGAL_ENTITY_SSBT CONSTANT VARCHAR2(40) := 'SSBT';
	C_BRANCH_GMBH CONSTANT VARCHAR2(40) := 'GmbH';
	
	
	--comment head
	C_COMMENT_HEAD CONSTANT VARCHAR2(100)	:= 'State Street:';
	
	--GEC_ASSET.SOURCE_FLAG
	C_SOURCE_FLAG_IR_AVAIL CONSTANT VARCHAR2(1) := 'I';
	C_SOURCE_FLAG_FTP_AVAIL CONSTANT VARCHAR2(1) := 'F';
	C_SOURCE_FLAG_IM_REQUEST CONSTANT VARCHAR2(1) := 'R';
	
	C_BOS_TIMEZONE CONSTANT VARCHAR2(20) := 'America/New_York'; 
	
	C_COMMENT_LENTH CONSTANT NUMBER := 4000;
	
	------------------HOLD UTIL --------------
	C_HOLD_UTIL_CMT CONSTANT VARCHAR2(100)  := 'Locate response will be updated at ';	
	C_HOLD_UTIL_DATE_FORMAT CONSTANT VARCHAR2(50)  := 'hh:mm am dd-MON-yyyy';	
	
	--LOCATE ID RESET
	C_LOCATE_ID_RESET_TYPE_AT_EOD CONSTANT VARCHAR2(100)   := 'RESET_LOCATE_ID_SEQ_EOD';
	C_LOCATE_ID_RESET_TYPE_AT_SOD CONSTANT VARCHAR2(100) := 'RESET_LOCATE_ID_SEQ_SOD';
	
	--Default rate
	C_DEFAULT_INDICATIVE_RATE CONSTANT GEC_LOCATE_PREBORROW.INDICATIVE_RATE%TYPE := 999;
	C_DEFAULT_NSB_RATE CONSTANT GEC_LOCATE_PREBORROW.NSB_RATE%TYPE := 999;
	
	--Accept Flag
	C_ACCEPT_BY_REQUEST_ID CONSTANT VARCHAR2(10)   := 'ABRID';
	C_ACCEPT_BY_LOCPRB_ID CONSTANT VARCHAR2(10)    := 'ABLPID';
	
	C_SOURCE_DUMMY CONSTANT VARCHAR2(30) :='Dummy - No Demand Borrow';
	
	-- borrow source type
	C_BORROW_FILE CONSTANT VARCHAR2(1) := 'F';
	C_BORROW_SINGLE CONSTANT VARCHAR2(1) := 'S';
	C_BORROW_BATCH CONSTANT VARCHAR2(1) := 'B';
	C_BORROW_FLIP CONSTANT VARCHAR2(2) :='FT';
	-- borrow input type
	C_BORROW_MANUAL_INPUT CONSTANT GEC_BORROW.TYPE%type := 'MANUAL';
	C_BORROW_AUTO_INPUT CONSTANT GEC_BORROW.TYPE%type := 'AUTO';
	
	-- dummy short source cd
	C_SOURCE_CD_MORE_DEMAND CONSTANT GEC_IM_ORDER.SOURCE_CD%type := 'Dummy - Borrow More Than Demand';
	C_SOURCE_CD_NO_DEMAND CONSTANT GEC_IM_ORDER.SOURCE_CD%type := 'Dummy - No Demand Borrow';
	
	-- borrow status
	C_BORROW_ERROR CONSTANT VARCHAR2(1) := 'E';
	C_BORROW_MANUAL CONSTANT VARCHAR2(1) := 'M';
	C_BORROW_PROCESSED CONSTANT VARCHAR2(1) := 'P';
	C_BORROW_TEMP CONSTANT VARCHAR2(1) := 'T';
	
	-- allocation status
	C_ALLO_TEMP CONSTANT VARCHAR2(1) := 'T';
	C_ALLO_PROCESSED CONSTANT VARCHAR2(1) := 'P';
	C_ALLO_BOOKED CONSTANT VARCHAR2(1) := 'B';
	
	-- borrow operation
	C_BORROW_ADD CONSTANT VARCHAR2(1) := 'A';
	C_BORROW_DELETE CONSTANT VARCHAR2(1) := 'D';
	C_BORROW_UPDATE CONSTANT VARCHAR2(1) := 'U';
	C_BORROW_BOOKED CONSTANT VARCHAR2(1) := 'B';
	
	-- borrow manual intervention reason
	C_BORROW_MORE_THAN_DEMAND CONSTANT GEC_BORROW.INTERVENTION_REASON%type := 'OVERBORROW';
	C_BORROW_SP CONSTANT GEC_BORROW.INTERVENTION_REASON%type := 'SP';
	C_BORROW_AUTO_BOOKING_NO CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= 'NOAUTOBOOKING';
	C_BORROW_NO_LOCATE_FEE CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= 'NOLOCATEFEE';
	C_BORROW_0189_LOAN CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= '0189LNINVALID';
	C_BORROW_0189_LOAN_RT CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= '0189LNRNINVALID';
	C_BORROW_NO_PREPAY_RATE CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= 'NOPREPAYRATE';
	C_BORROW_P_SHARE CONSTANT GEC_BORROW.INTERVENTION_REASON%type:= 'PSHARE';
	-- borrow request type
	C_BORROW_REQUEST_SB CONSTANT GEC_BORROW_REQUEST_TYPE.BORROW_REQUEST_TYPE%type:= 'SB';
	C_BORROW_REQUEST_NSB CONSTANT GEC_BORROW_REQUEST_TYPE.BORROW_REQUEST_TYPE%type:= 'NSB';
	C_BORROW_REQUEST_EQUILAND CONSTANT GEC_BORROW_REQUEST_TYPE.BORROW_REQUEST_TYPE%type:= 'Equiland';
	C_BORROW_REQUEST_OTHERS CONSTANT GEC_BORROW_REQUEST_TYPE.BORROW_REQUEST_TYPE%type:= 'Others';
	
	--BORROW ORDER STATUS
	C_BORROW_ORDER_INFLIGHT	CONSTANT GEC_BORROW_ORDER.STATUS%TYPE :='I';
	C_BORROW_ORDER_INFLIGHT_MSG	CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE :='In-Flight';
	
	--Borrow request export type
  	C_FILE_REQUEST			    CONSTANT GEC_BORROW_REQUEST.TYPE%TYPE :='FILE';
	C_AUTO_RELEASE_REQUEST	CONSTANT GEC_BORROW_REQUEST.TYPE%TYPE :='AUTO_EQL';
  	C_MANUAL_AUTO_REQUEST			CONSTANT GEC_BORROW_REQUEST.TYPE%TYPE :='MANUAL_EQL';
	
	C_TRADE_CNTRY_US CONSTANT VARCHAR(2) := 'US';
	C_TRADE_CNTRY_CA CONSTANT VARCHAR(2) := 'CA';
	C_TRADE_CNTRY_NON_US CONSTANT VARCHAR(6) := 'Non_US';
	
	C_LOCATE_FILE_UPLOAD CONSTANT VARCHAR(20) := 'FILE_UPLOAD';
	C_LOCATE_TRADER_ENTER CONSTANT VARCHAR(20) := 'TRADE_ENTER';
	C_LOCATE_CLIENT_ENTER CONSTANT VARCHAR(20) := 'CLIENT_ENTER';
	C_LOCATE_FUTURE_JOB CONSTANT VARCHAR(20) := 'FUTURE_JOB_ENTER';
	C_BORROW_MIN_PRICE CONSTANT GEC_BORROW.PRICE%TYPE := -123456789;
	C_EQUILEND CONSTANT VARCHAR(20) := 'Equilend';
	C_SB CONSTANT VARCHAR(20) := 'SB';
	C_REPORT CONSTANT VARCHAR(20) := 'Report';
    C_NSB CONSTANT VARCHAR(20) := 'NSB';
    C_EXTERNAL CONSTANT VARCHAR(20) := 'External';
	
    -- branch code
	C_BRANCH_BOS CONSTANT VARCHAR(20) := 'BOS';
	C_BRANCH_TOR CONSTANT VARCHAR(20) := 'TOR';
	
	-- 0189/DUMY FUND
	C_FUND_0189 CONSTANT VARCHAR(20) := '0189';	
	C_FUND_DUMY CONSTANT VARCHAR(20) := 'DUMY';		
	
	-- US / CA
	C_COUNTRY_US CONSTANT VARCHAR(3) := 'US';
	C_COUNTRY_CA CONSTANT VARCHAR(3) := 'CA';
	C_COUNTRY_AU CONSTANT VARCHAR(3) := 'AU';
	
    C_G1L CONSTANT GEC_G1_BOOKING.TRANSACTION_CD%TYPE := 'G1L';
	C_G1B CONSTANT GEC_G1_BOOKING.TRANSACTION_CD%TYPE := 'G1B';
	
	-- borrow request status
	C_REQUEST_IN_FLIGHT CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'I';
	C_REQUEST_PENDING CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'P';
	C_REQUEST_FAIL CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'F';	
	C_REQUEST_RESPONSE_RECEIVED CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'R';		
	C_REQUEST_PENDING_CANCEL CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'PC';		
	C_REQUEST_CANCELED CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'CC';	
	C_REQUEST_CLOSED CONSTANT GEC_BORROW_REQUEST.STATUS%TYPE := 'C';	
	
	-- borrow request status message
	C_REQUEST_M_IN_FLIGHT CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'In-Flight';
	C_REQUEST_M_PENDING CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Pending';
	C_REQUEST_M_FAIL CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Fail';	
	C_REQUEST_M_RESPONSE_RECEIVED CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Response Received';		
	C_REQUEST_M_PENDING_CANCEL CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Pending Cancel';		
	C_REQUEST_M_CANCELED CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Canceled';	
	C_REQUEST_M_CLOSED CONSTANT GEC_BORROW_REQUEST.STATUS_MSG%TYPE := 'Closed';
	
	-- borrow order status
	C_ORDER_IN_FLIGHT CONSTANT GEC_BORROW_ORDER.STATUS%TYPE := 'I';			
	C_ORDER_RESPONDED CONSTANT GEC_BORROW_ORDER.STATUS%TYPE := 'RR';	
	C_ORDER_PARTIALLY_CANCELLED CONSTANT GEC_BORROW_ORDER.STATUS%TYPE := 'PC';		
	C_ORDER_CANCELLED CONSTANT GEC_BORROW_ORDER.STATUS%TYPE := 'C';		
	C_ORDER_REJECTED CONSTANT GEC_BORROW_ORDER.STATUS%TYPE := 'R';	
	
	-- borrow order status message
	C_ORDER_M_IN_FLIGHT CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE := 'In-Flight';			
	C_ORDER_M_RESPONDED CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE := 'Responded';	
	C_ORDER_M_PARTIALLY_CANCELLED CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE := 'Partially Canceled';		
	C_ORDER_M_CANCELLED CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE := 'Canceled';		
	C_ORDER_M_REJECTED CONSTANT GEC_BORROW_ORDER.STATUS_MSG%TYPE := 'Rejected';		
	
	-- message type and subtype
	C_MESSAGE_TYPE_SHTT CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_TYPE%TYPE := 'SHTT';
	C_MESSAGE_TYPE_AGAC CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_TYPE%TYPE := 'AGAC';
	C_MESSAGE_TYPE_ORAC CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_TYPE%TYPE := 'ORAC';
	C_MESSAGE_TYPE_ERPA CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_TYPE%TYPE := 'ERPA';	
	C_MESSAGE_SUBTYPE_ABNO CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_SUB_TYPE%TYPE := 'ABNO';
	C_MESSAGE_SUBTYPE_ABCACO CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_SUB_TYPE%TYPE := 'ABCACO';
	C_MESSAGE_SUBTYPE_ABRE CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_SUB_TYPE%TYPE := 'ABRE'; 
	C_MESSAGE_SUBTYPE_ABINCO CONSTANT GEC_EQUILEND_MESSAGE.MESSAGE_SUB_TYPE%TYPE := 'ABINCO'; 
	
	-- flip trade status
	C_FLIP_TRADE_PENDING CONSTANT VARCHAR2(1) := 'P';
	C_FLIP_TRADE_MANUAL CONSTANT VARCHAR2(1) := 'M';
	
	  --BULK TRADE STATUS
  	C_BULK_TRADE_ERROR CONSTANT GEC_BULK_G1_TRADE.STATUS%TYPE := 'E';
  	C_BULK_TRADE_PENDING CONSTANT GEC_BULK_G1_TRADE.STATUS%TYPE := 'P';
  	C_BULK_TRADE_BOOKED CONSTANT GEC_BULK_G1_TRADE.STATUS%TYPE := 'B';
  	C_BULK_TRADE_EXPIRED CONSTANT GEC_BULK_G1_TRADE.STATUS%TYPE := 'X';
  	C_BULK_TRADE_ERROR_MSG CONSTANT GEC_BULK_G1_TRADE.STATUS_MSG%TYPE := 'Error';
  	C_BULK_TRADE_PENDING_MSG CONSTANT GEC_BULK_G1_TRADE.STATUS_MSG%TYPE := 'Pending';
  	C_BULK_TRADE_CASH	CONSTANT GEC_BULK_G1_TRADE.COLLATERAL_TYPE%TYPE := 'C';	
	C_BULK_TRADE_EXPIRED_MSG CONSTANT GEC_BULK_G1_TRADE.STATUS_MSG%TYPE := 'Expired';
	C_BULK_TRADE_COLLATERAL_TYPE_P	CONSTANT GEC_BULK_G1_TRADE.COLLATERAL_TYPE%TYPE := 'P';	
	
	-- head information
    C_CORP_ID CONSTANT NUMBER(2) := 2;
    C_TRADE_ID CONSTANT VARCHAR2(10) := 'SFP';
    
    --return max length of STATUS_MSG IN GEC_EQUILEND_MESSAGE
    C_MAX_LENGTH_STATUS_MSG CONSTANT NUMBER(4) := '500';
	FUNCTION GET_MAX_STATUS_MSG RETURN NUMBER;
	FUNCTION GET_SEC_RATE_REPORT_CONST RETURN VARCHAR2;
	
	--get dummy funds in gec_config table
	
	FUNCTION GET_DUMMY_FUNDS RETURN VARCHAR2;
	
	FUNCTION GET_DUMMYWITH0189_FUNDS RETURN VARCHAR2;
	BULK_RETURN_POSTYPE_BOTH CONSTANT GEC_BULK_G1_RETURN_TEMP.TRANSACTION_TYPE%type :='D';
	BULK_RETURN_POSTYPE_BORROW CONSTANT GEC_BULK_G1_RETURN_TEMP.TRANSACTION_TYPE%type :='B';
	BULK_RETURN_POSTYPE_LOAN CONSTANT GEC_BULK_G1_RETURN_TEMP.TRANSACTION_TYPE%type :='L';
	BULK_RETURN_ASSET_MISSING CONSTANT GEC_BULK_G1_RETURN_TEMP.ASSETCODE_ERROR_MSG%type := 'The Asset Code is required. Please input Asset Code.';
	BULK_RETURN_ASSET_NOT_FOUND CONSTANT GEC_BULK_G1_RETURN_TEMP.ASSETCODE_ERROR_MSG%type := 'The Security is not found.';
	BULK_RETURN_ASSET_MULTI_FOUND CONSTANT GEC_BULK_G1_RETURN_TEMP.ASSETCODE_ERROR_MSG%type := 'Multiple Security are found.';
	BULK_RETURN_TDATE_MISSING CONSTANT GEC_BULK_G1_RETURN_TEMP.TRADEDATE_ERROR_MSG%type := 'The Trade Date is required. Please input Trade Date.';
	BULK_RETURN_TDATE_HOLIDAY CONSTANT GEC_BULK_G1_RETURN_TEMP.TRADEDATE_ERROR_MSG%type := 'The trade date you entered is a non-trading date.';
	BULK_RETURN_SDATE_MISSING CONSTANT GEC_BULK_G1_RETURN_TEMP.SETTLEDATE_ERROR_MSG%type := 'The Settle Date is required. Please input Settle Date.';
	BULK_RETURN_SDATE_HOLIDAY CONSTANT GEC_BULK_G1_RETURN_TEMP.SETTLEDATE_ERROR_MSG%type := 'The settlement date you entered is a non-trading date.';
	BULK_RETURN_SDATE_LT_TDATE CONSTANT GEC_BULK_G1_RETURN_TEMP.SETTLEDATE_ERROR_MSG%type := 'The Settle Date should not be less than Trade Date.';
	BULK_RETURN_SDATE_PAST CONSTANT GEC_BULK_G1_RETURN_TEMP.SETTLEDATE_ERROR_MSG%type := 'The Settle Date cannot be past date.';
	BULK_RETURN_SHAREQTY_MISSING CONSTANT GEC_BULK_G1_RETURN_TEMP.SHAREQTY_ERROR_MSG%type :='The Quantity is required. Please input Quantity.';
	BULK_RETURN_BGREF_CPTY_VALUES CONSTANT GEC_BULK_G1_RETURN_TEMP.CPTYNAME_ERROR_MSG%type :='Return Branch,Return Cpty and Bargain Ref cannot be entered at a time.';
	BULK_RETURN_CPTY_IS_NOT_FOUND CONSTANT GEC_BULK_G1_RETURN_TEMP.CPTYNAME_ERROR_MSG%type :='Invalid Return Cpty - Please Verify.';
	BULK_RETURN_POST_TYPE_MISSING CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='The Posting Type is required. Please input Posting Type.';
	BULK_RETURN_POST_TYPE_NO_NEED CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='The Posting Type is not required.';
	BULK_RETURN_POST_TYPE_WRONG CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='Invalid Posting Type - please verify.';
	BULK_RETURN_B_FOR_CPTY CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='Posting Type can only be ''B'' when Return Cpty is blank.';
	BULK_RETURN_POST_TYPE_WARNING CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='Invalid Counterparty and Posting Type combination - please verify.';
	BULK_RETURN_B_FOR_BR CONSTANT GEC_BULK_G1_RETURN_TEMP.POSTYPE_ERROR_MSG%type :='Posting Type can only be ''B'' when Return Branch is selected.';
	BULK_RETURN_G1_INSTANCE_REQ CONSTANT GEC_BULK_G1_RETURN_TEMP.G1_INSTANCE_CD_ERROR_MSG%type :='The G1 Instance input is mandatory.  Please input G1 Instance.';
	BULK_RETURN_G1_INSTANCE_INV CONSTANT GEC_BULK_G1_RETURN_TEMP.G1_INSTANCE_CD_ERROR_MSG%type :='Invalid G1 Instance - Please Verify.';
end GEC_CONSTANTS_PKG;
/
create or replace package body GEC_CONSTANTS_PKG
as
DUMMY_FUNDS GEC_CONFIG.ATTR_VALUE1%type;
DUMY0189_FUNDS GEC_CONFIG.ATTR_VALUE1%type;

FUNCTION GET_MAX_STATUS_MSG RETURN NUMBER
	IS
	BEGIN
		RETURN C_MAX_LENGTH_STATUS_MSG;
	END GET_MAX_STATUS_MSG;
	
FUNCTION GET_SEC_RATE_REPORT_CONST RETURN VARCHAR2
	IS
  -- get C_SEC_RATE_REPORT_CONST for loadAvailSecRatesNotCorrectReport
    C_SEC_RATE_REPORT_CONST CONSTANT VARCHAR2(40) := 'SFPTRADER';
	BEGIN
		RETURN C_SEC_RATE_REPORT_CONST;
	END GET_SEC_RATE_REPORT_CONST;

FUNCTION GET_DUMMY_FUNDS RETURN VARCHAR2
      IS
      BEGIN
      IF DUMMY_FUNDS is  null THEN
      SELECT ATTR_VALUE1||',' into DUMMY_FUNDS from GEC_CONFIG where ATTR_GROUP='FUND' and ATTR_NAME='DUMY_FUND';
      END IF;
      RETURN DUMMY_FUNDS;
      END GET_DUMMY_FUNDS;
FUNCTION GET_DUMMYWITH0189_FUNDS RETURN VARCHAR2
      IS
      BEGIN
      IF DUMY0189_FUNDS is  null THEN
      SELECT ATTR_VALUE1||','||GEC_CONSTANTS_PKG.C_FUND_0189||',' into DUMY0189_FUNDS from GEC_CONFIG where ATTR_GROUP='FUND' and ATTR_NAME='DUMY_FUND';
      END IF;
      RETURN DUMY0189_FUNDS;
      END GET_DUMMYWITH0189_FUNDS;
end GEC_CONSTANTS_PKG;
/